server.port: 8001

spring.cloud.bus.refresh.enabled: true
spring.cloud.bus.env.enabled: true

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mbronshteyn/ConfigData
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh, bus-env
#  security:
#    enabled: false
