server.port: 8001

management.endpoints.web.exposure.include: all

spring.cloud.bus.refresh.enabled: true
spring.cloud.bus.env.enabled: true

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mbronshteyn/ConfigData
          clone-on-start: true

