spring:
  application:
    name: sentence
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/
#   server.port: ${PORT:${SERVER_PORT:0}}


management:
  server:
    port: 8082

eureka:
  client:
    healthcheck:
      enabled: true

